spring:
  redis:
    database: 0
    host: localhost
    port: 6379

# Show mybatis sql
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port:  ${port:8003}
#eureka:
#  instance:
#    instance-id: service-user-${server.port}.com
#  client:
#    proxy-host: localhost