############################################################
#
# Eureka cluster service
# Port: 7002 - 7004
#
############################################################
server:
  tomcat:
    uri-encoding: UTF-8
  port: ${port:7004}

############################################################
#
# 配置项目信息
#
############################################################
spring:
  application:
    name: eureka-cluster-04

eureka:
  instance:
    hostname: eureka-cluster-7004
    prefer-ip-address: true
    ip-address: ${spring.application.name}
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-cluster-7003.com:7003, http://eureka-cluster-7002.com:7002

management:
  health:
    redis:
      enabled: false

logging:
  level:
    com.netflix: warn